/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclesofinterestdesktop;

/**
 *
 * @author sdeje
 */
public class AddROIWindow extends javax.swing.JFrame {

    /**
     * Creates new form AddVOIWindow
     */
    public AddROIWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitle = new javax.swing.JLabel();
        jlbInterest = new javax.swing.JLabel();
        jlbDescription = new javax.swing.JLabel();
        jtfInterest = new javax.swing.JTextField();
        jtfDescription = new javax.swing.JTextField();
        jbtCancel = new javax.swing.JButton();
        jbtAdd = new javax.swing.JButton();
        jtbError = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VOI - Reason for Interest - Add");
        setPreferredSize(new java.awt.Dimension(410, 240));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlbTitle.setText("Add Reason for Interest");
        getContentPane().add(jlbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jlbInterest.setText("Reason *");
        getContentPane().add(jlbInterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jlbDescription.setText("Description *");
        getContentPane().add(jlbDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        getContentPane().add(jtfInterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 150, -1));
        getContentPane().add(jtfDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, -1));

        jbtCancel.setText("Cancel");
        jbtCancel.setToolTipText("");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jbtCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jbtAdd.setText("Add");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });
        getContentPane().add(jbtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 60, -1));

        jtbError.setEditable(false);
        jtbError.setText("Fields with an asterisk (*) are required");
        jtbError.setToolTipText("");
        jtbError.setBorder(null);
        jtbError.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        jtbError.setEnabled(false);
        jtbError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbErrorActionPerformed(evt);
            }
        });
        getContentPane().add(jtbError, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jtbError.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        try {
            String interest = jtfInterest.getText();
            String description = jtfDescription.getText();
            if (interest != null && !interest.trim().isEmpty()) {
                System.out.println("interest = " + interest);
            } else {
                throw new Exception("Null Pointer Error");
            }
            if (description != null && !description.trim().isEmpty()) {
                System.out.println("license = " + description);
            } else {
                throw new Exception("Null Pointer Error");
            }
            vc.createReasonOfInterest(interest, description);
            this.dispose();
        } catch (Exception e) {
            jtbError.setVisible(true);
            this.revalidate();
            System.out.println("------------");
        }
    }//GEN-LAST:event_jbtAddActionPerformed

    private void jtbErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbErrorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddROIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddROIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddROIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddROIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddROIWindow().setVisible(true);
            }
        });
    }
    VehiclesOfInterestController vc = new VehiclesOfInterestController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JLabel jlbDescription;
    private javax.swing.JLabel jlbInterest;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JTextField jtbError;
    private javax.swing.JTextField jtfDescription;
    private javax.swing.JTextField jtfInterest;
    // End of variables declaration//GEN-END:variables
}
