/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclesofinterestdesktop;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

/**
 *
 * @author sdeje
 */
public class DeleteVOIWindow extends javax.swing.JFrame {

    /**
     * Creates new form AddVOIWindow
     */
    private String license;
    private String reason;
    private String vMake;
    private String vModel;
    private String vYear;
    private String vColor;
    private String oName;
    private String oPhone;

    public DeleteVOIWindow() {
        initComponents();
    }

    public DeleteVOIWindow(String license, String reason, String vMake, String vModel, String vYear, String vColor, String oName, String oPhone) {
        initComponents();
        this.license = license;
        this.reason = reason;
        this.vMake = vMake;
        this.vModel = vModel;
        this.vYear = vYear;
        this.vColor = vColor;
        this.oName = oName;
        this.oPhone = oPhone;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitle = new javax.swing.JLabel();
        jlbLicense = new javax.swing.JLabel();
        jlbReason = new javax.swing.JLabel();
        jlbVehicleMake = new javax.swing.JLabel();
        jlbVehicleModel = new javax.swing.JLabel();
        jlbVehicleYear = new javax.swing.JLabel();
        jlbVehicleColor = new javax.swing.JLabel();
        jlbOwnerName = new javax.swing.JLabel();
        jlbOwnerPhone = new javax.swing.JLabel();
        jtfLicense = new javax.swing.JTextField();
        jtfOwnerName = new javax.swing.JTextField();
        jtfOwnerPhone = new javax.swing.JTextField();
        jbtCancel = new javax.swing.JButton();
        jbtDelete = new javax.swing.JButton();
        jcbReason = new javax.swing.JComboBox<>();
        jcbVehicleMake = new javax.swing.JComboBox<>();
        jcbVehicleModel = new javax.swing.JComboBox<>();
        jcbVehicleYear = new javax.swing.JComboBox<>();
        jcbVehicleColor = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VOI Inquiry - Delete");
        setPreferredSize(new java.awt.Dimension(400, 530));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlbTitle.setText("Delete VOI");
        getContentPane().add(jlbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 27, -1, -1));

        jlbLicense.setText("License Plate *");
        getContentPane().add(jlbLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, -1));

        jlbReason.setText("Reason for Interest *");
        getContentPane().add(jlbReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 105, 120, -1));

        jlbVehicleMake.setText("Vehicle Make *");
        getContentPane().add(jlbVehicleMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 143, 120, -1));

        jlbVehicleModel.setText("Vehicle Model *");
        getContentPane().add(jlbVehicleModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 181, 120, -1));

        jlbVehicleYear.setText("Vehicle Year *");
        getContentPane().add(jlbVehicleYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 219, 120, -1));

        jlbVehicleColor.setText("Vehicle Color *");
        getContentPane().add(jlbVehicleColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 257, 120, -1));

        jlbOwnerName.setText("Owner's Name *");
        getContentPane().add(jlbOwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 295, 120, -1));

        jlbOwnerPhone.setText("Owner's Phone Number *");
        getContentPane().add(jlbOwnerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 333, -1, -1));

        jtfLicense.setEnabled(false);
        getContentPane().add(jtfLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 68, 150, -1));

        jtfOwnerName.setEnabled(false);
        getContentPane().add(jtfOwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 292, 150, -1));

        jtfOwnerPhone.setEnabled(false);
        getContentPane().add(jtfOwnerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 330, 150, -1));

        jbtCancel.setText("Cancel");
        jbtCancel.setToolTipText("");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jbtCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 371, -1, -1));

        jbtDelete.setText("Delete");
        jbtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 371, 70, -1));

        jcbReason.setEditable(true);
        jcbReason.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbReason.setEnabled(false);
        getContentPane().add(jcbReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 102, 150, -1));

        jcbVehicleMake.setEditable(true);
        jcbVehicleMake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbVehicleMake.setEnabled(false);
        getContentPane().add(jcbVehicleMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 150, -1));

        jcbVehicleModel.setEditable(true);
        jcbVehicleModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbVehicleModel.setEnabled(false);
        getContentPane().add(jcbVehicleModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 178, 150, -1));

        jcbVehicleYear.setEditable(true);
        jcbVehicleYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbVehicleYear.setEnabled(false);
        jcbVehicleYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVehicleYearActionPerformed(evt);
            }
        });
        getContentPane().add(jcbVehicleYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 216, 150, -1));

        jcbVehicleColor.setEditable(true);
        jcbVehicleColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbVehicleColor.setEnabled(false);
        getContentPane().add(jcbVehicleColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 254, 148, -1));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 0, -1, 446));
        getContentPane().add(filler6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 10, 446));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbVehicleYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVehicleYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbVehicleYearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtfLicense.setText(license);
        jcbReason.removeAllItems();
        jcbReason.addItem(reason);
        jcbVehicleMake.removeAllItems();
        jcbVehicleMake.addItem(vMake);
        jcbVehicleModel.removeAllItems();
        jcbVehicleModel.addItem(vModel);
        jcbVehicleYear.removeAllItems();
        jcbVehicleYear.addItem(vYear);
        jcbVehicleColor.removeAllItems();
        jcbVehicleColor.addItem(vColor);
        jtfOwnerName.setText(oName);
        jtfOwnerPhone.setText(oPhone);

    }//GEN-LAST:event_formWindowOpened

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void jbtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeleteActionPerformed
        vc.deleteVehicleOfInterest(license);
        this.dispose();
    }//GEN-LAST:event_jbtDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteVOIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteVOIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteVOIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteVOIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteVOIWindow().setVisible(true);
            }
        });
    }
    VehiclesOfInterestController vc = new VehiclesOfInterestController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtDelete;
    private javax.swing.JComboBox<String> jcbReason;
    private javax.swing.JComboBox<String> jcbVehicleColor;
    private javax.swing.JComboBox<String> jcbVehicleMake;
    private javax.swing.JComboBox<String> jcbVehicleModel;
    private javax.swing.JComboBox<String> jcbVehicleYear;
    private javax.swing.JLabel jlbLicense;
    private javax.swing.JLabel jlbOwnerName;
    private javax.swing.JLabel jlbOwnerPhone;
    private javax.swing.JLabel jlbReason;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JLabel jlbVehicleColor;
    private javax.swing.JLabel jlbVehicleMake;
    private javax.swing.JLabel jlbVehicleModel;
    private javax.swing.JLabel jlbVehicleYear;
    private javax.swing.JTextField jtfLicense;
    private javax.swing.JTextField jtfOwnerName;
    private javax.swing.JTextField jtfOwnerPhone;
    // End of variables declaration//GEN-END:variables
}
