/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclesofinterestdesktop;

/**
 *
 * @author sdeje
 */
public class DeleteVehicleModelWindow extends javax.swing.JFrame {

    /**
     * Creates new form AddVOIWindow
     */
    public DeleteVehicleModelWindow() {
        initComponents();
    }

    public DeleteVehicleModelWindow(String model, String make) {
        initComponents();
        this.model = model;
        this.make = make;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitle = new javax.swing.JLabel();
        jlbMake = new javax.swing.JLabel();
        jbtCancel = new javax.swing.JButton();
        jbtDelete = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        JlbModel = new javax.swing.JLabel();
        jtfModel = new javax.swing.JTextField();
        jcbMake = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VOI - Vehicle Model - Delete");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlbTitle.setText("Delete Vehicle Model");
        getContentPane().add(jlbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 19, 310, -1));

        jlbMake.setText("Make *");
        getContentPane().add(jlbMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 62, 120, -1));

        jbtCancel.setText("Cancel");
        jbtCancel.setToolTipText("");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jbtCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 137, -1, -1));

        jbtDelete.setText("Delete");
        jbtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 137, 70, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 0, -1, 199));
        getContentPane().add(filler6, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 10, 199));

        JlbModel.setText("Model *");
        getContentPane().add(JlbModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 97, -1, -1));

        jtfModel.setEnabled(false);
        getContentPane().add(jtfModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 97, 150, -1));

        jcbMake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMakeActionPerformed(evt);
            }
        });
        getContentPane().add(jcbMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 57, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jcbMake.removeAllItems();
        jcbMake.addItem(make);
        jcbMake.setSelectedIndex(0);
        jtfModel.setText(model);

    }//GEN-LAST:event_formWindowOpened

    private void jcbMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMakeActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        this.dispose();       
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void jbtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeleteActionPerformed
        vc.deleteVehicleModel(jtfModel.getText());
this.dispose();
    }//GEN-LAST:event_jbtDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteVehicleModelWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteVehicleModelWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteVehicleModelWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteVehicleModelWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteVehicleModelWindow().setVisible(true);
            }
        });
    }
    private String model;
    private String make;
VehiclesOfInterestController vc = new VehiclesOfInterestController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlbModel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtDelete;
    private javax.swing.JComboBox<String> jcbMake;
    private javax.swing.JLabel jlbMake;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JTextField jtfModel;
    // End of variables declaration//GEN-END:variables
}
