/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclesofinterestdesktop;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

/**
 *
 * @author sdeje
 */
public class EditVOIWindow extends javax.swing.JFrame {

    private String license;
    private String reason;
    private String vMake;
    private String vModel;
    private String vYear;
    private String vColor;
    private String oName;
    private String oPhone;

    /**
     * Creates new form AddVOIWindow
     */
    public EditVOIWindow() {
        initComponents();
    }

    public EditVOIWindow(String license, String reason, String vMake, String vModel, String vYear, String vColor, String oName, String oPhone) {
        this.license = license;
        this.reason = reason;
        this.vMake = vMake;
        this.vModel = vModel;
        this.vYear = vYear;
        this.vColor = vColor;
        this.oName = oName;
        this.oPhone = oPhone;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitle = new javax.swing.JLabel();
        jlbLicense = new javax.swing.JLabel();
        jlbReason = new javax.swing.JLabel();
        jlbVehicleMake = new javax.swing.JLabel();
        jlbVehicleModel = new javax.swing.JLabel();
        jlbVehicleYear = new javax.swing.JLabel();
        jlbVehicleColor = new javax.swing.JLabel();
        jlbOwnerName = new javax.swing.JLabel();
        jlbOwnerPhone = new javax.swing.JLabel();
        jtfLicense = new javax.swing.JTextField();
        jtfOwnerName = new javax.swing.JTextField();
        jtfOwnerPhone = new javax.swing.JTextField();
        jbtCancel = new javax.swing.JButton();
        jbtEdit = new javax.swing.JButton();
        jtbError = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jcbReason = new javax.swing.JComboBox<>();
        jcbVehicleMake = new javax.swing.JComboBox<>();
        jcbVehicleModel = new javax.swing.JComboBox<>();
        jcbVehicleYear = new javax.swing.JComboBox<>();
        jcbVehicleColor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VOI Inquiry - Edit");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlbTitle.setText("Edit VOI");
        getContentPane().add(jlbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 310, -1));

        jlbLicense.setText("License Plate *");
        getContentPane().add(jlbLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 88, 120, -1));

        jlbReason.setText("Reason for Interest *");
        getContentPane().add(jlbReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 123, 120, -1));

        jlbVehicleMake.setText("Vehicle Make *");
        getContentPane().add(jlbVehicleMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 161, 120, -1));

        jlbVehicleModel.setText("Vehicle Model *");
        getContentPane().add(jlbVehicleModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 199, 120, -1));

        jlbVehicleYear.setText("Vehicle Year *");
        getContentPane().add(jlbVehicleYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 237, 120, -1));

        jlbVehicleColor.setText("Vehicle Color *");
        getContentPane().add(jlbVehicleColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 275, 120, -1));

        jlbOwnerName.setText("Owner's Name *");
        getContentPane().add(jlbOwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 313, 120, -1));

        jlbOwnerPhone.setText("Owner's Phone Number *");
        getContentPane().add(jlbOwnerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 351, -1, -1));

        jtfLicense.setEditable(false);
        jtfLicense.setEnabled(false);
        jtfLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLicenseActionPerformed(evt);
            }
        });
        getContentPane().add(jtfLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 86, 150, -1));
        getContentPane().add(jtfOwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 310, 150, -1));
        getContentPane().add(jtfOwnerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 348, 150, -1));

        jbtCancel.setText("Cancel");
        jbtCancel.setToolTipText("");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jbtCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 389, -1, -1));

        jbtEdit.setText("Edit");
        jbtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditActionPerformed(evt);
            }
        });
        getContentPane().add(jbtEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 389, 60, -1));

        jtbError.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtbError.setText("Fields with an asterisk (*) are required");
        jtbError.setBorder(null);
        jtbError.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        jtbError.setEnabled(false);
        getContentPane().add(jtbError, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 426, -1, -1));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 0, -1, 446));
        getContentPane().add(filler6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 10, 446));

        jcbReason.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbReason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbReasonActionPerformed(evt);
            }
        });
        getContentPane().add(jcbReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 120, 150, -1));

        jcbVehicleMake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbVehicleMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVehicleMakeActionPerformed(evt);
            }
        });
        getContentPane().add(jcbVehicleMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 158, 150, -1));

        jcbVehicleModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbVehicleModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 196, 150, -1));

        jcbVehicleYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbVehicleYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVehicleYearActionPerformed(evt);
            }
        });
        getContentPane().add(jcbVehicleYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 234, 150, -1));

        jcbVehicleColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbVehicleColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 272, 148, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbVehicleYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVehicleYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbVehicleYearActionPerformed

    private void jtfLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfLicenseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String[] reasons = vc.allReasonsForInterestKey();
        jcbReason.removeAllItems();
        jcbReason.addItem("");
        for (int x = 0; x < reasons.length; x++) {
            jcbReason.addItem(reasons[x]);
        }
        String[] vehicleMakes = vc.allVehicleMakeKey();
        jcbVehicleMake.removeAllItems();
        jcbVehicleMake.addItem("");
        for (int x = 0; x < vehicleMakes.length; x++) {
            jcbVehicleMake.addItem(vehicleMakes[x]);
        }
        jcbVehicleModel.removeAllItems();
        java.util.Date d = new java.util.Date();
        jcbVehicleYear.removeAllItems();
        for (int x = (int) d.getYear() + 1900 + 1; x >= 1980; x--) {
            jcbVehicleYear.addItem(String.valueOf(x));
        }
        jcbVehicleColor.removeAllItems();
        jcbVehicleColor.addItem("");
        String currentDirectory = new File("").getAbsolutePath();
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(currentDirectory + "\\src\\vehiclesofinterestdesktop\\colors.txt"));

            String str;
            while ((str = br.readLine()) != null) {
                jcbVehicleColor.addItem(str);
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        jtfLicense.setText(license);
        jtbError.setVisible(false);
        for (int x = 0; x < jcbReason.getItemCount(); x++) {
            if (jcbReason.getItemAt(x).equals(reason)) {
                jcbReason.setSelectedIndex(x);
            }
        }
        for (int x = 0; x < jcbVehicleMake.getItemCount(); x++) {
            if (jcbVehicleMake.getItemAt(x).equals(vMake)) {
                jcbVehicleMake.setSelectedIndex(x);
            }
        }
        String[][] cars = vc.allVehicleModel();
        jcbVehicleModel.removeAllItems();

        for (int x = 0; x < cars.length; x++) {
            try {
                if (cars[x][1].equals(jcbVehicleMake.getSelectedItem())) {
                    jcbVehicleModel.addItem(cars[x][0]);
                }
            } catch (Exception e) {
                jcbVehicleModel.removeAllItems();

            }
        }
        for (int x = 0; x < jcbVehicleModel.getItemCount(); x++) {
            if (jcbVehicleModel.getItemAt(x).equals(vMake)) {
                jcbVehicleModel.setSelectedIndex(x);
            }
        }
        for (int x = 0; x < jcbVehicleYear.getItemCount(); x++) {
            if (jcbVehicleYear.getItemAt(x).equals(vYear)) {
                jcbVehicleYear.setSelectedIndex(x);
            }
        }
        for (int x = 0; x < jcbVehicleColor.getItemCount(); x++) {
            if (jcbVehicleColor.getItemAt(x).equals(vColor)) {
                jcbVehicleColor.setSelectedIndex(x);
            }
        }
        jtfOwnerName.setText(oName);
        jtfOwnerPhone.setText(oPhone);
jtbError.setVisible(false);

    }//GEN-LAST:event_formWindowOpened

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void jbtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditActionPerformed
        try {

            String license = jtfLicense.getText();
            String reason = (String) jcbReason.getSelectedItem();
            String vMake = (String) jcbVehicleMake.getSelectedItem();
            String vModel = (String) jcbVehicleModel.getSelectedItem();
            String vYear = (String) jcbVehicleYear.getSelectedItem();
            String vColor = (String) jcbVehicleColor.getSelectedItem();
            String oName = (String) jtfOwnerName.getText();
            String oPhone = (String) jtfOwnerPhone.getText();
            if (license != null && !license.trim().isEmpty()) {
                System.out.println("license = " + license);
            } else {
                throw new Exception("Null Pointer Error");
            }
            if (reason != null && !reason.trim().isEmpty()) {
                System.out.println("Reason for Interest = " + reason);
            } else {
                throw new Exception("Null Pointer Error");
            }
            if (vMake != null && !vMake.trim().isEmpty()) {
                System.out.println("Vehicle Make = " + vMake);
            } else {
                throw new Exception("Null Pointer Error");
            }
            if (vModel != null && !vModel.trim().isEmpty()) {
                System.out.println("Vehicle Model = " + vModel);
            } else {
                throw new Exception("Null Pointer Error");
            }
            if (vYear != null && !vYear.trim().isEmpty()) {
                System.out.println("Vehicle Year = " + vYear);
            } else {
                throw new Exception("Null Pointer Error");
            }
            if (vColor != null && !vColor.trim().isEmpty()) {
                System.out.println("Vehicle Color = " + vColor);
            } else {
                throw new Exception("Null Pointer Error");
            }
            if (oName != null && !oName.trim().isEmpty()) {
                System.out.println("Owner's Name = " + oName);
            } else {
                throw new Exception("Null Pointer Error");
            }
            if (oPhone != null && !oPhone.trim().isEmpty()) {
                System.out.println("Owner's Phone Number = " + oPhone);
            }

            vc.updateVehicleOfInterest(license, reason, vMake, vModel, vYear, vColor, oName, oPhone);
            this.dispose();
        } catch (Exception e) {

            jtbError.setVisible(true);
            this.revalidate();
            System.out.println("------------");
        }
    }//GEN-LAST:event_jbtEditActionPerformed

    private void jcbVehicleMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVehicleMakeActionPerformed
        String[][] cars = vc.allVehicleModel();
        jcbVehicleModel.removeAllItems();
        for (int x = 0; x < cars.length; x++) {
            try {
                if (cars[x][1].equals(jcbVehicleMake.getSelectedItem())) {
                    jcbVehicleModel.addItem(cars[x][0]);
                }
            } catch (Exception e) {
                jcbVehicleModel.removeAllItems();

            }
        }
    }//GEN-LAST:event_jcbVehicleMakeActionPerformed

    private void jcbReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbReasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbReasonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditVOIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditVOIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditVOIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditVOIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditVOIWindow().setVisible(true);
            }
        });
    }
    VehiclesOfInterestController vc = new VehiclesOfInterestController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtEdit;
    private javax.swing.JComboBox<String> jcbReason;
    private javax.swing.JComboBox<String> jcbVehicleColor;
    private javax.swing.JComboBox<String> jcbVehicleMake;
    private javax.swing.JComboBox<String> jcbVehicleModel;
    private javax.swing.JComboBox<String> jcbVehicleYear;
    private javax.swing.JLabel jlbLicense;
    private javax.swing.JLabel jlbOwnerName;
    private javax.swing.JLabel jlbOwnerPhone;
    private javax.swing.JLabel jlbReason;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JLabel jlbVehicleColor;
    private javax.swing.JLabel jlbVehicleMake;
    private javax.swing.JLabel jlbVehicleModel;
    private javax.swing.JLabel jlbVehicleYear;
    private javax.swing.JTextField jtbError;
    private javax.swing.JTextField jtfLicense;
    private javax.swing.JTextField jtfOwnerName;
    private javax.swing.JTextField jtfOwnerPhone;
    // End of variables declaration//GEN-END:variables
}
