/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclesofinterestdesktop;

/**
 *
 * @author sdeje
 */
public class EditVehicleMakeWindow extends javax.swing.JFrame {

    /**
     * Creates new form AddVOIWindow
     */
    public EditVehicleMakeWindow() {
        initComponents();
    }

    public EditVehicleMakeWindow(String make) {
        this.make = make;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitle = new javax.swing.JLabel();
        jlbMake = new javax.swing.JLabel();
        jtfMake = new javax.swing.JTextField();
        jbtCancel = new javax.swing.JButton();
        jbtEdit = new javax.swing.JButton();
        jtbError = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VOI - Vehicle Make - Edit");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlbTitle.setText("Edit Vehicle Make");
        getContentPane().add(jlbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 20, 310, -1));

        jlbMake.setText("Make");
        getContentPane().add(jlbMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, -1));
        getContentPane().add(jtfMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 150, -1));

        jbtCancel.setText("Cancel");
        jbtCancel.setToolTipText("");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jbtCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jbtEdit.setText("Edit");
        jbtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditActionPerformed(evt);
            }
        });
        getContentPane().add(jbtEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 60, -1));

        jtbError.setText("Fields with an Asterisk (*) are required");
        jtbError.setBorder(null);
        jtbError.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        jtbError.setEnabled(false);
        getContentPane().add(jtbError, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 270, -1));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 190));
        getContentPane().add(filler6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 10, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void jbtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditVehicleMakeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditVehicleMakeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditVehicleMakeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditVehicleMakeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditVehicleMakeWindow().setVisible(true);
            }
        });
    }
    VehiclesOfInterestController vc = new VehiclesOfInterestController();
    private String make;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtEdit;
    private javax.swing.JLabel jlbMake;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JTextField jtbError;
    private javax.swing.JTextField jtfMake;
    // End of variables declaration//GEN-END:variables
}
