/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclesofinterestdesktop;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sdeje
 */
public class ViewVehicleOfInterestWindow extends javax.swing.JFrame {

    /**
     * Creates new form InquiryWindow
     */
    public ViewVehicleOfInterestWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtAdd = new javax.swing.JButton();
        jbtEdit = new javax.swing.JButton();
        jbtDelete = new javax.swing.JButton();
        jbtSearch = new javax.swing.JButton();
        jtbSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtlVOI = new javax.swing.JTable();
        jbtRefresh = new javax.swing.JButton();
        jbtReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VOI Inquiry - View Vehicle of Interest");
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtAdd.setText("Add");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVOIButtonClicked(evt);
            }
        });
        getContentPane().add(jbtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, 124, 63));

        jbtEdit.setText("Edit");
        jbtEdit.setEnabled(false);
        jbtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVOIButtonClicked(evt);
            }
        });
        getContentPane().add(jbtEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 33, 124, 63));

        jbtDelete.setText("Delete");
        jbtDelete.setEnabled(false);
        jbtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVOIButtonClicked(evt);
            }
        });
        getContentPane().add(jbtDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 33, 124, 63));

        jbtSearch.setText("Search");
        jbtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jbtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 114, 100, 35));

        jtbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jtbSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 114, 176, 35));

        jtlVOI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "License Plate", "Reason", "Make", "Model", "Vehicle Yr", "Color", "Owner's Name", "Owner's Phone #"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jtlVOI.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            jtlVOIFocusGained(evt);
        }
    });
    jtlVOI.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jtlVOIMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jtlVOI);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 156, 776, 409));

    jbtRefresh.setText("Refresh");
    jbtRefresh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbtRefreshActionPerformed(evt);
        }
    });
    getContentPane().add(jbtRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 572, 124, 63));

    jbtReturn.setText("Return to Main");
    jbtReturn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbtReturnActionPerformed(evt);
        }
    });
    getContentPane().add(jbtReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 572, 124, 63));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtReturnActionPerformed
        //this button can close the current window.

        super.dispose();
    }//GEN-LAST:event_jbtReturnActionPerformed

    private void AddVOIButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVOIButtonClicked
        // Creates ADD window and provides required information        
        AddVOIWindow aw = new AddVOIWindow();
        aw.show();
    }//GEN-LAST:event_AddVOIButtonClicked

    private void editVOIButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVOIButtonClicked
        // Creates edit window and provides required information
        int selectedRow = jtlVOI.getSelectedRow();
        ArrayList<String> row = new ArrayList<String>();
        for (int x = 0; x < 8; x++) {
            row.add((String) jtlVOI.getValueAt(selectedRow, x));
        }
        System.out.println(row.get(0) + " " + row.get(1) + " " + row.get(2) + " " + row.get(3) + " " + row.get(4) + " " + row.get(5) + " " + row.get(6) + " " + row.get(7));
        EditVOIWindow ew = new EditVOIWindow(row.get(0), row.get(1), row.get(2), row.get(3), row.get(4), row.get(5), row.get(6), row.get(7));
        ew.show();
    }//GEN-LAST:event_editVOIButtonClicked

    private void deleteVOIButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVOIButtonClicked
        //Creates delete window
        int selectedRow = jtlVOI.getSelectedRow();
        ArrayList<String> row = new ArrayList<String>();
        for (int x = 0; x < 8; x++) {
            row.add((String) jtlVOI.getValueAt(selectedRow, x));
        }
        System.out.println(row.get(0) + " " + row.get(1) + " " + row.get(2) + " " + row.get(3) + " " + row.get(4) + " " + row.get(5) + " " + row.get(6) + " " + row.get(7));
        DeleteVOIWindow dw = new DeleteVOIWindow(row.get(0), row.get(1), row.get(2), row.get(3), row.get(4), row.get(5), row.get(6), row.get(7));
        
        dw.show();
    }//GEN-LAST:event_deleteVOIButtonClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Populates table
        DefaultTableModel model = (DefaultTableModel) jtlVOI.getModel();
        jtlVOI.removeAll();
        String[] VOIList = vc.allVehicleOfInterestKey();
        for (int x = 0; x < VOIList.length; x++) {
            model.addRow(vc.getVehicleOfInterestByLicenase(VOIList[x]));
        }
        //set up accelerators.
        jbtRefresh.setMnemonic(KeyEvent.VK_R);
        jbtRefresh.setToolTipText("Alt+R - Retrieves updated database entries");
        jbtAdd.setMnemonic(KeyEvent.VK_A);
        jbtAdd.setToolTipText("Alt+A - Adds new Vehicle of Interest");
        jbtEdit.setMnemonic(KeyEvent.VK_E);
        jbtEdit.setToolTipText("Alt+E - Edit Selected Vehicle of Interest");
        jbtDelete.setMnemonic(KeyEvent.VK_D);
        jbtDelete.setToolTipText("Alt+D - Delete Selected Vehicle of Interest");
        jbtReturn.setMnemonic(KeyEvent.VK_C);
        jbtReturn.setToolTipText("Alt+C; Closes view screen and returns to main menu");
        jtbSearch.setToolTipText("Insert Vehicle's License Plate");
        jtlVOI.setToolTipText("Select row to enable more options");

    }//GEN-LAST:event_formWindowOpened

    private void jtlVOIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtlVOIFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtlVOIFocusGained

    private void jbtRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRefreshActionPerformed
        //Repopulates database  and set edit and delete buttons to disable      
        DefaultTableModel model = (DefaultTableModel) jtlVOI.getModel();
        model.setRowCount(0);
        String[] VOIList = vc.allVehicleOfInterestKey();
        for (int x = 0; x < VOIList.length; x++) {
            model.addRow(vc.getVehicleOfInterestByLicenase(VOIList[x]));
        }
        jbtEdit.setEnabled(false);
        jbtDelete.setEnabled(false);

    }//GEN-LAST:event_jbtRefreshActionPerformed

    private void jtlVOIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtlVOIMouseClicked
        //When a row is clicked, it enables the edit and delete buttons.  Reclicking a selected row will de-select it.
        int selection = jtlVOI.getSelectedRow();
        if (selection == table_state) {
            jtlVOI.clearSelection();
            selection = jtlVOI.getSelectedRow();
            
        }
        System.out.println(selection);
        if (selection >= 0) {
            jbtEdit.setEnabled(true);
            jbtDelete.setEnabled(true);
        } else {
            jbtEdit.setEnabled(false);
            jbtDelete.setEnabled(false);
        }
        table_state = selection;

    }//GEN-LAST:event_jtlVOIMouseClicked

    private void jtbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbSearchActionPerformed
    }//GEN-LAST:event_jtbSearchActionPerformed

    private void jbtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchActionPerformed
        String[] vehicle = vc.getVehicleOfInterestByLicenase(jtbSearch.getText());
        DefaultTableModel model = (DefaultTableModel) jtlVOI.getModel();
        model.setRowCount(0);
        model.addRow(vc.getVehicleOfInterestByLicenase(jtbSearch.getText()));

    }//GEN-LAST:event_jbtSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVehicleOfInterestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVehicleOfInterestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVehicleOfInterestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVehicleOfInterestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVehicleOfInterestWindow().setVisible(true);
            }
        });
    }
    private VehiclesOfInterestController vc = new VehiclesOfInterestController();
    private int table_state = -1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtDelete;
    private javax.swing.JButton jbtEdit;
    private javax.swing.JButton jbtRefresh;
    private javax.swing.JButton jbtReturn;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JTextField jtbSearch;
    private javax.swing.JTable jtlVOI;
    // End of variables declaration//GEN-END:variables
}
